#1) Do not share the contents of this file with untrusted users
#2) You may copy this file on all your servers if you wish to share items on different servers, especially
#   locale servers used to create your items (Rule 1 still counts)
#3) Do not change the content of this file, changing values may make some of your items unusable
#----------------------------------------------------------------------------